config/routes.rb
Billwaldo::Application.routes.draw do
  resource :bills, :only => [:new, :create]

  match "bills/:uuid", :as => "bills_view", :to => "bills#show"
  match "bills/:uuid/expenses/create", :as => "expenses_create", :to => "expenses#create"
  match "bills/:uuid/people/create", :as => "people_create", :to => "bills#add_person"

  root :to => "bills#new"
end

app/models/account.rb
class Account
  include Mongoid::Document
  include Mongoid::Timestamps  

  field :balance, :type => BigDecimal

  belongs_to :bill
  embedded_in :person

  def add_credit(amount)
    self.balance += amount
  end

  def add_debit(amount)
    self.balance -= amount
  end
end

app/models/bill.rb
class Bill
  include Mongoid::Document
  include Mongoid::Timestamps
  
  attr_protected :uuid
  before_create :gen_uuid
  before_save :update_payments

  field :uuid, :type => String
  field :name, :type => String, :default => "Unnamed"
  has_and_belongs_to_many :people
  embeds_many :expenses
  embeds_many :payments

  accepts_nested_attributes_for :people
  accepts_nested_attributes_for :expenses, :allow_destroy => true
  accepts_nested_attributes_for :payments, :allow_destroy => true

  def add_expense(expense)
    self.expenses << expense
    expense.update_balances
  end

  protected
  def gen_uuid
    self.uuid = SecureRandom.hex
  end
  
  def update_payments
    if !self.people.empty?
      self.payments.clear
      calculate_next_payment
    end
  end

  def calculate_next_payment
    debitor = self.people.min_by do |p| p.balance(self) end
    creditor = self.people.max_by do |p| p.balance(self) end
    if debitor.has_pending_debit self and creditor.has_pending_credit self
      create_payment_and_update_balances debitor, creditor
      calculate_next_payment
    end
  end
  
  def create_payment_and_update_balances(debitor, creditor)
    amount = [creditor.absolute_balance(self), debitor.absolute_balance(self)].min
    self.payments.create!(:amount => amount, :creditor => creditor, :debitor => debitor)
    debitor.add_credit self, amount
    creditor.add_debit self, amount    
  end
end

app/models/expense.rb
# encoding: utf-8
class Expense
  include Mongoid::Document
  include Mongoid::Timestamps  

  field :description, :type => String
  field :amount, :type => BigDecimal

  embedded_in :bill

  has_and_belongs_to_many :creditors, :class_name => "Person"
  has_and_belongs_to_many :debitors, :class_name => "Person"
  
  accepts_nested_attributes_for :creditors, :allow_destroy => true
  accepts_nested_attributes_for :debitors, :allow_destroy => true

  def creditors_list
    listize(self.creditors)
  end

  def debitors_list
    listize(self.debitors)
  end

  def update_balances
    cred_count = self.creditors.count
    deb_count = self.debitors.count
    self.creditors.each do |cred|
      cred.add_credit self.bill, self.amount / cred_count
      cred.save
    end
   
    self.debitors.each do |deb|
      deb.add_debit self.bill, self.amount / deb_count
      deb.save
    end    
  end

  protected
  def listize(list, separator = ", ")
    list.map(&:name).join(separator)
  end
end

app/models/payment.rb
# encoding: utf-8
class Payment
  include Mongoid::Document
  include Mongoid::Timestamps

  field :amount, :type => Float
  field :paid_flag, :type => Boolean, :default => false

  embedded_in :bill

  belongs_to_related :creditor, :class_name => "Person"
  belongs_to_related :debitor, :class_name => "Person"
  
  def ==(other)
    self.amount == other.amount && self.creditor == other.creditor && self.debitor == other.debitor
  end
end

app/models/person.rb
class Person
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, :type => String
  field :finished_flag, :type => Boolean, :default => false
  
  has_and_belongs_to_many :bills
  
  embeds_many :accounts

  accepts_nested_attributes_for :accounts, :allow_destroy => true
  
  def add_credit(bill, amount)
    get_account(bill).add_credit amount
  end
  
  def add_debit(bill, amount)
    get_account(bill).add_debit amount
  end
  
  def balance(bill)
    get_account(bill).balance
  end
  
  def absolute_balance(bill)
    balance(bill).abs
  end
  
  def get_account(bill)
    accounts.each do |account|
      return account if account.bill == bill
    end
    new_account = Account.new(:person => self, :bill => bill, :balance => 0)
    accounts << new_account
    new_account
  end
  
  def has_pending_debit(bill)
    balance(bill) <= 0.01
  end
  
  def has_pending_credit(bill)
    balance(bill) >= 0.01
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def new
    @bill = Bill.new

    respond_to do |format|
      format.html
    end
  end

  def create
    bill_params = params[:bill]
    
    if bill_params[:name].empty?
      @bill = Bill.new
    else
      @bill = Bill.new(:name => bill_params[:name])
    end

    respond_to do |format|
      if @bill.save
        format.html { redirect_to bills_view_path(@bill.uuid) }
      else
        format.html { render :action => :new }
      end
    end
  end

  def show
    @bill = Bill.where(:uuid => params[:uuid]).first

    respond_to do |format|
      if @bill
        format.html
      else
        format.html { redirect_to root_path, :notice => "Sorry, we couldn't find your bill." }
      end
    end
  end

  def add_person
    @bill = Bill.where( :uuid => params[ :uuid ]).first
    @bill.people << Person.new( params[ :person ])
    @bill.reload

    respond_to do |format|
      format.html { render :partial => "expenses/form" }
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  # POST /bills/:uuid/expenses
  def create
    @bill = Bill.where(:uuid => params[:uuid]).first
    @expense = Expense.new params[:expense]
    @bill.add_expense(@expense)
    
    if @bill.save
      notice = "#{@expense.description} - saved."
    else
      notice = "Eep, something went wrong saving your expense."
    end
    
    respond_to do |format|
      format.html { redirect_to bills_view_path(@bill.uuid), notice: notice }
    end
  end

  # DELETE /bills/:uuid/expenses/1
  # TODO: so people can remove mistaken expenses
  def destroy
    @bill = Bill.where(:uuid => params[:uuid]).first
    @expense = Expense.find(params[:id])
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to bills_view_path(@bill.uuid) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/bills/_add_person.html.erb
<%
  @person = @person || Person.new
%>

<%= form_for @person, :remote => true, :url => people_create_path( @bill.uuid ) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Name your bill</h2>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/new.html.erb
<p id="notice"><%= notice %></p>
<h1>Bill Waldo</h1>
<%= render 'form' %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @bill.name %> - Bill</h1>

<div id="add-person">
  <h2>Add a person</h2>
  <%= render :partial => "add_person" %>
</div>

<div id="add-expense">
  <h2>Add an expense</h2>
  <%= render :partial => "expenses/form" %>
</div>

<div id="list-expenses">
  <h2>Expenses list</h2>
<% if @bill.expenses.blank? %>
  <p id="no-expenses">
    Nothing to see here. No expenses, zip, zilch.
  </p>
<% else %>
  <% @bill.expenses.each do |exp| %>
    <p>
      <%= "#{exp.creditors_list} paid " %> £ <%= "#{exp.amount} for \"#{exp.description}\" on behalf of #{exp.debitors_list}" %>
    </p>
  <% end %>
<% end %>
</div>

<div id="list-payments">
  <h2>Payments list</h2>
<% if @bill.payments.blank? %>
  <p id="no-expenses">
    Nothing to pay for.
  </p>
<% else %>
  <% @bill.payments.each do |pay| %>
    <p>
      <%= "#{pay.debitor.name} owes #{pay.creditor.name} : " %> £ <%= "#{pay.amount}" %>
    </p>
  <% end %>
<% end %>
</div>

app/views/expenses/_form.html.erb
<%
  exp = Expense.new
%>

<%= form_for exp, :url => expenses_create_path( @bill.uuid ) do |f| %>
  <div class="field">
    <%= f.label :creditors %><br />
    <%= f.select(:creditors, @bill.people.collect { |p| [ p.name, p.id ] }, {}, { :multiple => "multiple" }) %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :amount %> (£)<br />
    <%= f.text_field :amount %>
  </div>

  <div class="field">
    <%= f.label :debitors %><br />
    <%= f.select(:debitors, @bill.people.collect { |p| [ p.name, p.id ] }, {}, { :multiple => "multiple" }) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Billwaldo</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>